---
title: "True Lies: Response to Reviewers"
author: "David Hugh-Jones"
date: "27/02/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Dear Nikos,

Thank you for the chance to revise this manuscript. I here respond to your comments and those of 
both reviewers.

> The most obvious comment that both reviewers made is one of etiquette: you are unnecessarily harsh
> to GSV! I would like you to reframe the discussion of GSV following the suggestions of R2. (And yes,
> the “don’t use the GSV method” in the conclusion should be replaced with something more informative
> and less pedantic.)

I have tried to be nicer, while simultaneously making it clear that using GSV is not a good idea.
I've changed my conclusion.

> I also like R2’s suggestion about either providing power calculations (see the example table this
> reviewer provided) and/or an online calculator that you will discuss in your paper. 

I now give examples of how to use my freely available R software to do power calculations,
and to analyse data from experiments.

> Finally, please
> ensure that you address R1’s comments on clarity.

I have done my best. See below.

With best wishes,

David Hugh-Jones


# Reviewer 1

My thanks go to reviewer 1 for his or her useful comments. I respond to individual points below.

> I think that the statistical argument could be explained more clearly... 

R1's understanding of the statistical argument is correct. I have given some similar examples. 
I hope this clarifies the argument, but I am open to further 
suggestions in case it is still a tough read.

> I also think that it would be important to explain more clearly how the statistical and conceptual
> arguments relate to the lack of nominal coverage of the estimator and its biasedness. This is not
> very clear at the moment - I am referring in particular to the last four paragraphs of page 4. In
> particular, I struggle to see how the two arguments can help explain the poor nominal coverage of
> the GSV method.

I've added an example, as follows:

"For example, if 3 out of 3 subjects report heads, the GSV software reports a lower bound of 100% for
any confidence interval. Indeed, since anyone who had the opportunity to lie clearly did so, this is
the correct lower bound (assuming we arbitrarily set *Lies = 1* in the case that $T = N$). But it
makes no sense as a confidence interval for $\lambda$: we clearly can't rule out that one or two
subjects truly saw heads, and would have reported tails if they had seen tails."

 
> In those paragraphs, it would also be useful to make a clearer distinction between the GSV method as
> an estimator of the proportion of lies actually told in the sample ("Lies") - and the problems that
> arise there; and the method as an estimate of the proportion of liars in the sample ("lambda"). At
> the moment the paper goes back and forth between the problems that arise in either case, which is
> confusing.

I've reorganized this section to avoid the back and forth.

> This is also true in the following sections ("Alternative methods" and "Point estimates"). As far 
> as I understand, the exercise here consists in comparing across methods the coverage and point 
> estimates of lambda (this is confusingly referred to as "Liars" in this part of the paper). 
> It would be useful to point this out more clearly.

I've corrected the mistaken terminology.


> I also thought that the part on "empirical Bayes" is not very well explained. Indeed, I wondered
> whether the inclusion of this section may detract from the overall value of the paper, since it
> becomes slightly less focused. The same goes for table 9 and corresponding text in the paper - it
> seems that this goes somewhat beyond the scope of the paper - which in my opinion works best as a
> comment focused on the GSV method, rather than its applications in subsequent papers.

I have made the empirical Bayes section much shorter, just briefly describing the approach. I've kept
the discussion of applications, because it is important to point out where the GSV method
has led researchers astray, but I have now put all this discussion in one place, including a brief
discussion of empirical Bayes results for Hugh-Jones (2016).

> However, I think that the first precept, "Do not use the GSV method", is perhaps too strong. I think
> that the simulations presented in the paper convinced me that GSV is not a good method to estimate
> the proportion of liars ("lambda"), espcially in comparison with the alternative methods - but I am
> less convinced that the method is a terrible estimator of the proportion of lies actually told in
> the sample ("Lies"). The simulations in the Appendix do not seem to show a very large bias or
> dramatic drops in coverage in this case.

I have removed this comment. I still would not use GSV to estimate "Lies". When the number of
reports is high, confidence intervals remain much too narrow (coverage of 70% or less), even with
a large N. See Figure 5 in the new paper. The bias is also never better than the naive estimator
and often worse.


> I also liked the thought experiment presented in the concluding section. However, one important
> point to make here is that, in such an experiment, each subject would face a different truthful
> distribution (and the experiment would not be able to control or observe which subject faced which
> distribution). We know from existing research that the underlying distribution matters for the
> willingness to lie. So this is a caveat to keep in mind when estimating the proportion of lies via
> this method.

I hope I am getting this right: although previous draws change the true distribution, if subjects do
not observe the outcome of previous draws, then their expectation should always be that they have a
$T/N$ chance of getting a white ball. See also reviewer 2's comment.

> Finally, I have some additional minor comments:

> - p. 1, footnote 1: the acronym GSV is used before it has been explained
> - p. 4: line 33, equation 1 should contain R/N, not R.

Fixed.

> - p. 4, table 3: what does "Percentage of cases" mean?

It was the percentage of simulation runs which had e.g. $R/N$ between 0 and 0.25. I
have clarified this.

> - Figure 3 in the Appendix, the horizontal axis is missing

The x axis serves only to separate Bayesian, Frequentist and GSV methods. I've used a bar 
chart to lessen any ambiguity.

# Reviewer 2

Thank you to reviewer 2 for his or her helpful suggestions.

> Power Calculations: I believe one area that would be extremely useful for future research would be 
> to provide some power calculations based on your proposed method (either frequentist or Bayesian).

> Online Calculator: Another way the paper could be extremely valuable for future researchers would 
> be, like GSV, to provide an online lying calculator so that researchers can easily use your 
> improved method.

Agreed. My original R software is available online. I now include an example of
how to use it for power calculations, point estimates, and confidence intervals.

> Suggested experiment in the concluding section: While I like the objective of the suggested
> experiment, I do not think the design works as I think it changes the nature/implication of lying...
> in the second experiment, if a subject gets the white ball but lies and reports black, then there is
> only one outcome for the experiment: both subjects will report black, and it will be with certainty
> that the experimenter will know one of the subjects will have lied. This seems like it a potentially
> important difference that could affect the willingness of subjects to lie.

This is a fair point and I don't see a way round this disadvantage either. I think the idea is worth
floating, but I have pointed out this weakness:

"Because the experimenter now knows exactly the number of liars, and liars themselves will
understand this, this changes the incentives to lie slightly (maybe subjects don't like giving the
experimenter certain knowledge that somebody lied)."

> Tone down the negative attention to GSV, and get directly to your solution. Your method is the 
> critical contribution, and make it central. Comparisons of the CIs in the simulations make this
> immediately clear. 

I am now politer to GSV and focus more on my alternative. I do want to make it clear that GSV 
confidence intervals are a step backward from what was out there already, and it would be a bad
idea to use them (I did point this out to the authors in 2016...!) But I now get quickly to the 
Bayesian method and leave discussion of GSV to later.


